version: '3'

services:
  serverless_graphql_lambda:
    container_name: serverless_graphql_lambda
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - AWS_ACCESS_KEY=$AWS_ACCESS_KEY
        - AWS_SECRET_KEY=$AWS_SECRET_KEY
        - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    command: yarn start:dev
